CREATE TABLE public.credit_card_balance (
	sk_id_bureau int4 NULL,
	sk_id_curr int4 NULL,
	months_balance int4 NULL,
	amt_balance numeric(15, 2) NULL,
	amt_credit_limit_actual int4 NULL,
	amt_drawings_atm_current float8 NULL,
	amt_drawings_current float8 NULL,
	amt_drawings_other_current float8 NULL,
	amt_drawings_pos_current float8 NULL,
	amt_inst_min_regularity float8 NULL,
	amt_payment_current float8 NULL,
	amt_payment_total_current float8 NULL,
	amt_receivable_principal float8 NULL,
	amt_recivable float8 NULL,
	amt_total_receivable float8 NULL,
	cnt_drawings_atm_current float8 NULL,
	cnt_drawings_current int4 NULL,
	cnt_drawings_other_current float8 NULL,
	cnt_drawings_pos_current float8 NULL,
	cnt_instalment_mature_cum float8 NULL,
	name_contract_status varchar(30) NULL,
	sk_dpd int4 NULL,
	sk_dpd_def int4 NULL
);