CREATE TABLE public.bureau (
	sk_id_curr int4 NULL,
	sk_id_bureau int4 NOT NULL,
	credit_active varchar(50) NULL,
	credit_currency varchar(50) NULL,
	days_credit int4 NULL,
	credit_day_overdue int4 NULL,
	days_credit_enddate numeric NULL,
	days_enddate_fact numeric NULL,
	amt_credit_max_overdue numeric(15, 2) NULL,
	cnt_credit_prolong int4 NULL,
	amt_credit_sum numeric(15, 2) NULL,
	amt_credit_sum_debt numeric(15, 2) NULL,
	amt_credit_sum_limit numeric(15, 2) NULL,
	amt_credit_sum_overdue numeric(15, 2) NULL,
	credit_type varchar(100) NULL,
	days_credit_update int4 NULL,
	amt_annuity numeric(15, 2) NULL,
	CONSTRAINT bureau_pkey PRIMARY KEY (sk_id_bureau)
);