CREATE TABLE bureau (
    SK_ID_CURR              INTEGER,
    SK_ID_BUREAU            INTEGER PRIMARY KEY,
    CREDIT_ACTIVE           VARCHAR(50),
    CREDIT_CURRENCY         VARCHAR(50),
    DAYS_CREDIT             INTEGER,
    CREDIT_DAY_OVERDUE      INTEGER,
    DAYS_CREDIT_ENDDATE     NUMERIC,
    DAYS_ENDDATE_FACT       NUMERIC,
    AMT_CREDIT_MAX_OVERDUE  NUMERIC(15, 2),
    CNT_CREDIT_PROLONG      INTEGER,
    AMT_CREDIT_SUM          NUMERIC(15, 2),
    AMT_CREDIT_SUM_DEBT     NUMERIC(15, 2),
    AMT_CREDIT_SUM_LIMIT    NUMERIC(15, 2),
    AMT_CREDIT_SUM_OVERDUE  NUMERIC(15, 2),
    CREDIT_TYPE             VARCHAR(100),
    DAYS_CREDIT_UPDATE      INTEGER,
    AMT_ANNUITY             NUMERIC(15, 2)
);

COPY public.bureau FROM 'C:/Home Credit Default Risk/Home-Credit-Default-Risk/data/bureau.csv' WITH (FORMAT csv, HEADER true, DELIMITER ',', ENCODING 'UTF8');