CREATE TABLE credit_card_balance(
	SK_ID_BUREAU    INTEGER,
	SK_ID_CURR INTEGER,
	MONTHS_BALANCE INTEGER,
	AMT_BALANCE NUMERIC(15, 2),
	AMT_CREDIT_LIMIT_ACTUAL INTEGER,
	AMT_DRAWINGS_ATM_CURRENT FLOAT,
	AMT_DRAWINGS_CURRENT FLOAT,
	AMT_DRAWINGS_OTHER_CURRENT FLOAT,
	AMT_DRAWINGS_POS_CURRENT FLOAT,
	AMT_INST_MIN_REGULARITY FLOAT,
	AMT_PAYMENT_CURRENT FLOAT,
	AMT_PAYMENT_TOTAL_CURRENT FLOAT,
	AMT_RECEIVABLE_PRINCIPAL FLOAT,
	AMT_RECIVABLE FLOAT,
	AMT_TOTAL_RECEIVABLE FLOAT,
	CNT_DRAWINGS_ATM_CURRENT FLOAT,
	CNT_DRAWINGS_CURRENT INTEGER,
	CNT_DRAWINGS_OTHER_CURRENT FLOAT,
	CNT_DRAWINGS_POS_CURRENT FLOAT,
	CNT_INSTALMENT_MATURE_CUM FLOAT,
	NAME_CONTRACT_STATUS VARCHAR(30),
	SK_DPD INTEGER,
	SK_DPD_DEF INTEGER
);

COPY public.bureau_balance FROM 'C:/Home Credit Default Risk/Home-Credit-Default-Risk/data/bureau_balance.csv' 
WITH (FORMAT csv, HEADER true, DELIMITER ',', ENCODING 'UTF8');